### ISSUE TITLE
libRCTARKit.a not found

### ISSUE THREAD

**Issue by kristabell** [HippoAR/react-native-arkit#24]
If follow the steps for "mostly automatic installation", I get the following error: 

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'i.getCameraPosition')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'i.getCamera..., stack:

If I follow the steps for "manual installation" and add libRCTARKit.a to the 'Link Binary With Libraries' configuration, I get the error:

'no such file or directory: (...)/Build/Products/Release-iphoneos/libRCTARKit.a''. 

I pulled down the RCTARKit.xcodeproj and it looks like libRCTARKit.a has the error 'React/RCTBridgeModule.h' file not found

**Comment by aurodatateam** [comment]
Have you tried updating your iOS and xCode versions to the Beta Releases?

**Comment by sw-yx** [comment]
hi @aurodatateam and others, i am facing this same problem too. "Library not found for -IRCTARKit" . latest iOS 11 and Xcode 9.

**Comment by sw-yx** [comment]
solved by manually adding the library and making sure source control was disabled.

**Comment by kristabell** [comment]
I solved by creating a new project with react-native init. It turns out it doesn't work with create react native apps that have been ejected

**Comment by sw-yx** [comment]
cool! suggest you close issue

**Comment by SujinParkdev** [comment]
hello. I have the same problem with you. 
after founded this solution, I created a new project with react-native init. 
but I still can't find libRCTARKit.a in my project folder.
